### ISSUE TITLE
Assets/Scripts/Projection/PositionLinker.cs(18,13): error CS0101: The namespace `global::' already contains a definition for `LinkingMode'

### ISSUE THREAD

**Issue by TRvanRossum** [thijser/ARGAME#6]
This is an error I got while building. Thijs, it seems like you worked on this class, could you please fix the namespace? I'm not sure which namespace it belongs to.

**Comment by ptrckkrmr** [comment]
It's in the `Projection` namespace. This error can be fixed by declaring the correct namespace for the class (the message indicates it currently resides in the "global" namespace). Wrapping the entire file contents in `namespace Projection { ... }` should fix it.

**Comment by ptrckkrmr** [comment]
Fixed in a recent commit (8d4af8c).
